{% set name = "gst-plugins-bad" %}
{% set version = "1.20.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-{{ version }}.tar.xz
  sha256: 7a11c13b55dd1d2386dd902219e41cbfcdda8e1e0aa3e738186c95074b35da4f

build:
  number: 1
  skip: true  # [osx]
  run_exports:
    # remove symbols at .90 patch releases just before minor versions?
    #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
    - {{ pin_subpackage('gst-plugins-bad', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    # expat here is _only_ required for mesa-dri-drivers
    - {{ cdt('expat') }}                 # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - pkg-config
    - perl
    - libtool  # [unix]
    - meson
    - ninja
  host:
    - libiconv
    - gstreamer
    - gst-plugins-base
    - gobject-introspection  # [linux]
    - glib
    - gettext                            # [osx]
    - libxcb                             # [linux]
    - pthread-stubs                      # [linux]
    - openssl
    - xorg-libx11  # [linux]
    - libxml2
    - libsndfile
    - libopus
  run:
    - gstreamer
    - gst-plugins-base
    - xorg-libx11  # [linux]
    - libopus

test:
  commands:
    - test -f $PREFIX/lib/gstreamer-1.0/libgstaiff${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstaudiovisualizers${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstcoloreffects${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstfbdevsink${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstgeometrictransform${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstjpegformat${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstmpegpsmux${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstrtmp2${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstsndfile${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgsttranscode${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstvideofiltersbad${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstvideoparsersbad${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstaiff.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstaudiovisualizers.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstcoloreffects.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstd3d.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstdirectsoundsrc.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstgeometrictransform.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstjpegformat.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstmpegpsmux.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstrtmp2.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstsndfile.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gsttranscode.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstvideofiltersbad.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstvideoparsersbad.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstwasapi.dll exit 1  # [win]
    - gst-inspect-1.0 --plugin audiovisualizers

about:
  home: http://gstreamer.freedesktop.org/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: GStreamer Bad Plug-ins
  dev_url: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad

extra:
  recipe-maintainers:
    - scopatz
    - kuepe-sl
