{% set name = "gst-plugins-bad" %}
{% set version = "1.24.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-{{ version }}.tar.xz
  sha256: e90f26c7dc9c76f4aa599b758cfd6d8c10d6a0b9cb265ba2c3c9bdf3888558f8
  patches:
    # https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3022
    - disable_d3d11_in_nvcodec.patch

build:
  number: 0
  # hmaarrfk 2023/12/10
  # Meson on windows seems to have a hard time
  # finding pkg-config with python 3.12
  skip: true  # [win and py!=311]
  run_exports:
    # remove symbols at .90 patch releases just before minor versions?
    #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
    - {{ pin_subpackage('gst-plugins-bad', max_pin='x.x') }}
  ignore_run_exports_from:   # [win]
    - python                 # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - gettext-tools
    - pkg-config
    - perl
    - libtool             # [unix]
    - python              # [win]
    - meson
    - ninja
    - zlib
  host:
    - python               # [win]
    - libiconv
    - gstreamer         {{ version }}
    - gst-plugins-base  {{ version }}
    - gobject-introspection              # [linux]
    - glib
    - libintl-devel                      # [not linux]
    - libxcb                             # [linux]
    - pthread-stubs                      # [linux]
    - openssl
    - libxml2
    - libsndfile
    - libopus
    # hmaarrfk
    # I'm pretty sure when we removed the static libraries
    # pkgconfig stopped working for anything that links privately to zlib
    - zlib
    - xorg-libx11                        # [linux]
    - xorg-libxfixes                     # [linux]
    - xorg-libxext                       # [linux]
    - xorg-xproto                        # [linux]
    - xorg-libx11                        # [linux]
    - expat                              # [linux]
    - xorg-libxrender                    # [linux]
    - xorg-libxdamage                    # [linux]
    - xorg-libxxf86vm                    # [linux]
    - xorg-libxau                        # [linux]
  run:
    # We want to pin harder than the run_export from gstreamer
    - gstreamer         {{ version }}

test:
  commands:
    # fbdevsink = Linux framebuffer video sink
    - test -f $PREFIX/lib/gstreamer-1.0/libgstfbdevsink${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstaiff${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstaudiovisualizers${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstcoloreffects${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstgeometrictransform${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstjpegformat${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstmpegpsmux${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstrtmp2${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstsndfile${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgsttranscode${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstvideofiltersbad${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstvideoparsersbad${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstaiff.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstaudiovisualizers.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstcoloreffects.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstd3d.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstdirectsoundsrc.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstgeometrictransform.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstjpegformat.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstmpegpsmux.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstrtmp2.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstsndfile.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gsttranscode.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstvideofiltersbad.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstvideoparsersbad.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstwasapi.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstnvcodec.dll exit 1    # [win]
    - gst-inspect-1.0 --plugin audiovisualizers

about:
  home: http://gstreamer.freedesktop.org/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: GStreamer Bad Plug-ins
  dev_url: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/tree/main/subprojects/gst-plugins-bad

extra:
  recipe-maintainers:
    - scopatz
    - kuepe-sl
    - hmaarrfk
